[[section-architecture-constraints]]
== Architecture Constraints

[role="help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****

=== Technical Constraints

[width="100%",cols="1,5,10",options="header"]
.List of Technical Constraints
|===
|  
| Conventions 
| Background and / or motivation  

3+| Software and programming constraints

| TC1
|
|

3+| Operating System Constraints

| TCn
|
|

3+| Hardware Constraints

| TCn
|
|
|===

=== Organizational Constraints

[width="100%",cols="1,5,10",options="header"]
.List of Organizational Constraints
|===
|  
| Conventions 
| Background and / or motivation  

| OC1
| Team
| 

| OC2
| Timeschedule
| 

| OC3
| IDE independent project setup
| No need to continue the editor and IDE wars. The project must be compilable on the command line via standard build tools.
|===

=== Conventions

[width="100%",cols="1,5,10",options="header"]
.List of Conventions
|===
|  
| Conventions 
| Background and / or motivation  

| C1
| Architecture documentation
| Structure based on the english arc42-Template version 7.0 with modified chapters to fit in C4 Model Diagrams and descriptions.
|===
